# Build stage
FROM maven:3.9.3-eclipse-temurin-17 AS build
WORKDIR /app
COPY ./devtasks/pom.xml ./pom.xml
COPY ./devtasks/src ./src
RUN mvn clean package -DskipTests

# Runtime stage
FROM eclipse-temurin:17-jdk-jammy
WORKDIR /app
COPY --from=build /app/target/devtasks-0.0.1-SNAPSHOT.jar ./devtasks.jar
CMD ["java", "-jar", "devtasks.jar"]
